// Code generated by github.com/arran4/go-subcommand/cmd/gosubc. DO NOT EDIT.

package main

//go:generate sh -c "command -v gosubc >/dev/null 2>&1 && gosubc generate || go run github.com/arran4/go-subcommand/cmd/gosubc generate"

import (
	"fmt"
	"os"

	"github.com/arran4/directoryGrouperBySize/cmd"
)

var (
	version = "dev"
	commit  = "none"
	date    = "unknown"
)

// Provenance
var (
	GeneratorVersion = "v0.0.31-0.20260930024605-d0b9c49facb9"
	GeneratedAt      = "2026-10-01T06:51:08Z"
	ProjectCommit    = "c6560e29fe570130d8bac31d0a977adabb92a1b7"
)

func main() {
	root, err := NewRoot("directoryGrouperBySize", version, commit, date)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		os.Exit(1)
	}

	if err := root.Execute(os.Args[1:]); err != nil {
		if e, ok := err.(*cmd.ErrExitCode); ok {
			if e.Err != nil {
				fmt.Fprintf(os.Stderr, "Error: %v\n", e.Err)
			}
			os.Exit(e.Code)
		}
		fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		os.Exit(1)
	}
}
