// Code generated by github.com/arran4/go-subcommand/cmd/gosubc. DO NOT EDIT.

package main

import (
	"testing"
)

func TestRoot_Execute(t *testing.T) {
	cmd, err := NewRoot("test", "", "", "")
	if err != nil {
		t.Fatalf("Failed to create root command: %v", err)
	}

	called := false
	cmd.CommandAction = func(c *RootCmd) error {
		called = true
		return nil
	}

	args := []string{}
	args = append(args, "--maxsize")
	args = append(args, "test")
	args = append(args, "-f")
	args = append(args, "test")
	args = append(args, "--scan")
	args = append(args, "test")
	args = append(args, "--fit-decreasing")
	args = append(args, "test")
	args = append(args, "-0")
	args = append(args, "--null")
	args = append(args, "--version")

	err = cmd.Execute(args)
	if err != nil {
		t.Errorf("Unexpected error: %v", err)
	}
	if !called {
		t.Error("CommandAction was not called")
	}

	if cmd.maxsize != "test" {
		t.Errorf("Expected maxsize to be 'test', got '%v'", cmd.maxsize)
	}
	if cmd.f != "test" {
		t.Errorf("Expected f to be 'test', got '%v'", cmd.f)
	}
	if cmd.scan != "test" {
		t.Errorf("Expected scan to be 'test', got '%v'", cmd.scan)
	}
	if cmd.strategy != "test" {
		t.Errorf("Expected strategy to be 'test', got '%v'", cmd.strategy)
	}
	if cmd.nulFlag0 != true {
		t.Errorf("Expected nulFlag0 to be true, got '%v'", cmd.nulFlag0)
	}
	if cmd.nulFlagNull != true {
		t.Errorf("Expected nulFlagNull to be true, got '%v'", cmd.nulFlagNull)
	}
	if cmd.versionFlag != true {
		t.Errorf("Expected versionFlag to be true, got '%v'", cmd.versionFlag)
	}

}

func TestRoot_ExecuteHelpAndUnknownFlags(t *testing.T) {
	cmd, err := NewRoot("test", "", "", "")
	if err != nil {
		t.Fatalf("Failed to create root command: %v", err)
	}

	if err := cmd.Execute([]string{"--help"}); err != nil {
		t.Errorf("--help returned an error: %v", err)
	}
	if err := cmd.Execute([]string{"-h"}); err != nil {
		t.Errorf("-h returned an error: %v", err)
	}
	if err := cmd.Execute([]string{"--not-a-real-flag"}); err == nil {
		t.Error("expected an error for an unknown long flag")
	}
	if err := cmd.Execute([]string{"-?"}); err == nil {
		t.Error("expected an error for an unknown short flag")
	}
}
