// Code generated by github.com/arran4/go-subcommand/cmd/gosubc. DO NOT EDIT.

package main

import (
	"errors"
	"flag"
	"fmt"
	"io"
	"os"
	"slices"
	"sync"

	"github.com/arran4/directoryGrouperBySize"
	"github.com/arran4/directoryGrouperBySize/cmd"
	"github.com/arran4/directoryGrouperBySize/cmd/directoryGrouperBySize/templates"
)

type Cmd interface {
	Execute(args []string) error
	Usage()
}

type InternalCommand struct {
	Exec      func(args []string) error
	UsageFunc func()
}

func (c *InternalCommand) Execute(args []string) error {
	return c.Exec(args)
}

func (c *InternalCommand) Usage() {
	c.UsageFunc()
}

func NewLazyCommand(f func() Cmd) func() Cmd {
	var once sync.Once
	var cmd Cmd
	return func() Cmd {
		once.Do(func() {
			cmd = f()
		})
		return cmd
	}
}

type UserError struct {
	Err error
	Msg string
}

func (e *UserError) Error() string {
	if e.Err != nil {
		return fmt.Sprintf("%s: %v", e.Msg, e.Err)
	}
	return e.Msg
}

func NewUserError(err error, msg string) *UserError {
	return &UserError{Err: err, Msg: msg}
}

func executeUsage(out io.Writer, templateName string, data any) error {
	return templates.GetTemplates().ExecuteTemplate(out, templateName, data)
}

type RootCmd struct {
	*flag.FlagSet
	Commands      map[string]func() Cmd
	Version       string
	Commit        string
	Date          string
	maxsize       string
	f             string
	scan          string
	strategy      string
	nulFlag0      bool
	nulFlagNull   bool
	versionFlag   bool
	CommandAction func(c *RootCmd) error
}

func (c *RootCmd) Usage() {
	err := executeUsage(os.Stderr, "directoryGrouperBySize_usage.txt", UsageDataRootCmd{c, false})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *RootCmd) UsageRecursive() {
	err := executeUsage(os.Stderr, "directoryGrouperBySize_usage.txt", UsageDataRootCmd{c, true})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

type UsageDataRootCmd struct {
	*RootCmd
	Recursive bool
}

func NewRoot(name, version, commit, date string) (*RootCmd, error) {
	c := &RootCmd{
		FlagSet:  flag.NewFlagSet(name, flag.ExitOnError),
		Commands: make(map[string]func() Cmd),
		Version:  version,
		Commit:   commit,
		Date:     date,
	}
	c.FlagSet.Usage = c.Usage

	c.StringVar(&c.maxsize, "maxsize", "", "Maximum size per disk with optional unit suffix (default GB)")

	c.StringVar(&c.f, "f", "", "File to read data from")

	c.StringVar(&c.scan, "scan", "", "Directory to scan internally (logical/apparent byte sizes)")

	c.StringVar(&c.strategy, "fit-decreasing", "first-fit-decreasing", "Grouping algorithm strategy to use: first (default, reorders inputs for efficient bin packing) or next (preserves original input order)")
	c.StringVar(&c.strategy, "strategy", "first-fit-decreasing", "Grouping algorithm strategy to use: first (default, reorders inputs for efficient bin packing) or next (preserves original input order)")
	c.StringVar(&c.strategy, "fit", "first-fit-decreasing", "Grouping algorithm strategy to use: first (default, reorders inputs for efficient bin packing) or next (preserves original input order)")

	c.BoolVar(&c.nulFlag0, "0", false, "Use zero bytes to separate records")

	c.BoolVar(&c.nulFlagNull, "null", false, "Use zero bytes to separate records")

	c.BoolVar(&c.versionFlag, "version", false, "Print version information and exit")

	c.CommandAction = func(c *RootCmd) error {

		err := directoryGrouperBySize.DirectoryGrouperBySize(c.maxsize, c.f, c.scan, c.strategy, c.nulFlag0, c.nulFlagNull, c.versionFlag)
		if err != nil {
			if errors.Is(err, cmd.ErrPrintHelp) {
				c.Usage()
				return nil
			}
			if errors.Is(err, cmd.ErrHelp) {
				fmt.Fprintf(os.Stderr, "Use '%s help' for more information.\n", os.Args[0])
				return nil
			}
			if e, ok := err.(*cmd.ErrExitCode); ok {
				return e
			}
			return fmt.Errorf("directoryGrouperBySize failed: %w", err)
		}
		return nil
	}

	c.Commands["help"] = func() Cmd {
		return &InternalCommand{
			Exec: func(args []string) error {
				if slices.Contains(args, "-deep") {
					c.UsageRecursive()
					return nil
				}
				c.Usage()
				return nil
			},
			UsageFunc: c.Usage,
		}
	}
	c.Commands["usage"] = func() Cmd {
		return &InternalCommand{
			Exec: func(args []string) error {
				if slices.Contains(args, "-deep") {
					c.UsageRecursive()
					return nil
				}
				c.Usage()
				return nil
			},
			UsageFunc: c.Usage,
		}
	}
	c.Commands["version"] = func() Cmd {
		return &InternalCommand{
			Exec: func(args []string) error {
				fmt.Printf("Version: %s\nCommit: %s\nDate: %s\n", c.Version, c.Commit, c.Date)
				return nil
			},
			UsageFunc: func() {
				fmt.Fprintf(os.Stderr, "Usage: %s version\n", os.Args[0])
			},
		}
	}
	return c, nil
}

func (c *RootCmd) Execute(args []string) (err error) {
	var remainingArgs []string
	dashDashSeen := false

	c.FlagSet = flag.NewFlagSet(c.FlagSet.Name(), flag.ContinueOnError)
	c.FlagSet.Usage = c.Usage

	// Create a local flagset so it doesn't ExitOnError or panic
	fs := flag.NewFlagSet(c.FlagSet.Name(), flag.ContinueOnError)
	fs.Usage = c.Usage

	fs.StringVar(&c.maxsize, "maxsize", c.maxsize, "Maximum size per disk with optional unit suffix (default GB)")

	fs.StringVar(&c.f, "f", c.f, "File to read data from")

	fs.StringVar(&c.scan, "scan", c.scan, "Directory to scan internally (logical/apparent byte sizes)")

	fs.StringVar(&c.strategy, "strategy", c.strategy, "Grouping algorithm strategy to use: first (default, reorders inputs for efficient bin packing) or next (preserves original input order)")
	fs.StringVar(&c.strategy, "fit-decreasing", c.strategy, "Grouping algorithm strategy to use: first (default, reorders inputs for efficient bin packing) or next (preserves original input order)")
	fs.StringVar(&c.strategy, "fit", c.strategy, "Grouping algorithm strategy to use: first (default, reorders inputs for efficient bin packing) or next (preserves original input order)")

	fs.BoolVar(&c.nulFlag0, "nulFlag0", c.nulFlag0, "Use zero bytes to separate records")
	fs.BoolVar(&c.nulFlag0, "0", c.nulFlag0, "Use zero bytes to separate records")

	fs.BoolVar(&c.nulFlagNull, "nulFlagNull", c.nulFlagNull, "Use zero bytes to separate records")
	fs.BoolVar(&c.nulFlagNull, "null", c.nulFlagNull, "Use zero bytes to separate records")

	fs.BoolVar(&c.versionFlag, "versionFlag", c.versionFlag, "Print version information and exit")
	fs.BoolVar(&c.versionFlag, "version", c.versionFlag, "Print version information and exit")

	err = fs.Parse(args)
	if err != nil {
		if err == flag.ErrHelp {
			return nil
		}
		return err
	}

	remainingArgs = fs.Args()

	// A proper scan handles values attached vs detached and booleans safely to determine exact boundaries
	parsedArgsCount := len(args) - len(remainingArgs)
	if parsedArgsCount > 0 && args[parsedArgsCount-1] == "--" {
		// Verify if it was consumed as a value by the preceding flag
		wasValue := false
		if parsedArgsCount >= 2 {
			prevArg := args[parsedArgsCount-2]
			if len(prevArg) > 0 && prevArg[0] == '-' {
				prevName := prevArg[1:]
				if len(prevName) > 0 && prevName[0] == '-' {
					prevName = prevName[1:]
				}
				eqIdx := -1
				for i, c := range prevName {
					if c == '=' {
						eqIdx = i
						break
					}
				}
				if eqIdx == -1 {
					f := fs.Lookup(prevName)
					if f != nil {
						if bf, ok := f.Value.(interface{ IsBoolFlag() bool }); !ok || !bf.IsBoolFlag() {
							wasValue = true
						}
					}
				}
			}
		}
		if !wasValue {
			dashDashSeen = true
		}
	} else if parsedArgsCount < len(args) && args[parsedArgsCount] == "--" {
		// we didn't consume it.
	}
	if c.CommandAction != nil {
		if err := c.CommandAction(c); err != nil {
			return fmt.Errorf("directoryGrouperBySize failed: %w", err)
		}
	}

	if !dashDashSeen && len(remainingArgs) > 0 {
		if cmd, ok := c.Commands[remainingArgs[0]]; ok {
			return cmd().Execute(remainingArgs[1:])
		}
	}
	return nil
}
